import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppThemeProvider from "./components/AppThemeProvider";
const inter = Inter({ subsets: ["latin"] });
import ReduxProvider from "./components/ReduxProvider";
export const metadata: Metadata = {
  title: "Admin App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
        <AppThemeProvider>
          {children}
        </AppThemeProvider>
        </ReduxProvider>
        </body>
    </html>
  );
}
